#!/bin/sh
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${KEYCLOAK_DB}"

$POSTGRES <<EOSQL
CREATE DATABASE ${KEYCLOAK_DB} OWNER ${KEYCLOAK_DB};
EOSQL

echo "Creating database: ${FARM_BASE_DB}"

$POSTGRES <<EOSQL
CREATE DATABASE ${FARM_BASE_DB} OWNER ${FARM_BASE_DB};
EOSQL

echo "Creating database: ${SCHEDULER_DB}"

$POSTGRES <<EOSQL
CREATE DATABASE ${SCHEDULER_DB} OWNER ${SCHEDULER_DB};
EOSQL

echo "Creating database: ${KONG_DB}"

$POSTGRES <<EOSQL
CREATE DATABASE ${KONG_DB} OWNER ${KONG_DB};
EOSQL
